#include "pa_shared.h"

const char* PA_STATE_LOOKUP[5] = {"NOT_READY", "READY", "ERROR", "TERMINATED", "UNKOWN" };
const char* PA_CONTEXT_STATE_LOOKUP[7] = {"UNCONNECTED", "CONNECTING", "AUTHORIZING", "SETTING_NAME", "READY", "FAILED", "TERMINATED" };
